var mongoose = require("mongoose");

const OrganizationProgramSchema = new mongoose.Schema(
  {
    id: { type: String },
    organizationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "organization",
      index: true,
    },
    projectId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "project",
      index: true,
    },
    programId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "program",
      index: true,
    },
    Deal_Organization_ID: { type: Number, index: true },
    WRG_Organization_ID: { type: Number, index: true },
    DealId: { type: String, index: true },
    Previous_Year_Overall_Rank: { type: String },
    Previous_Year_Winner: { type: String },
    Previous_Category_Rank: { type: String },
    Email_to_Send_EA_to: { type: String },
    Email_to_Send_Portal_to: { type: String },
    Email_to_Send_Reporting_Website_Login_to: { type: String },
    Previous_Year_Category: { type: String },
    Surveys_Sent: { type: Number },
    Current_Year_Overall_Rank: { type: String },
    Survey_Type: { type: String },
    Current_Year_Winner: { type: String },
    Current_Year_Category_Rank: { type: String },
    Current_Year_Category: { type: String },
    Total_Number_of_Program_EEs: { type: String },
    Total_Number_of_National_EEs: { type: String },
    National_EEs: { type: String },
    National_EE_Count: { type: Number },
    Program_EEs: { type: String },
    Program_EE_Count: { type: Number },
    Total_Number_of_Global_Employees: { type: String },
    PR_Contact_Last_Name: { type: String },
    PR_Contact_Email: { type: String },
    PR_Contact_Phone: { type: String },
    PR_Contact_First_Name: { type: String },
    Payment_Amount: { type: String },
    Payment_Method: { type: String },
    Stage: { type: String },
    //e-com fields
    WBC_Access: { type: String, default: null },
    BBP_Access: { type: String, default: null },
    EV_Sorting_Filter: { type: String, default: null },
    EV_Access: { type: String, default: null },
    CR_Access: { type: String, default: null },
    RD_Access: { type: String, default: null },
    Annual_Trend_Access: { type: String, default: null },
    KIA_Access: { type: String, default: null },
    WFR_Access: { type: String, default: null },
    RR_by_Demographic_Fee: { type: String, default: null },
    WFR_Payment_Details: { type: String, default: null },
    Last_time_deal_synced: { type: String, default: null },
    Annual_Trend_Payment_Details: { type: String, default: null },
    EV_Payment_Details: { type: String, default: null },
    RD_Payment_Details: { type: String, default: null },
    WBC_Payment_Details: { type: String, default: null },
    EV_Sorting_Payment_Details: { type: String, default: null },
    CR_Payment_Details: { type: String, default: null },
    BBP_Payment_Details: { type: String, default: null },
    KIA_Payment_Details: { type: String, default: null },
    Data_Resort_Payment_Details: { type: String, default: null },
    FDD_Payment_Details: { type: String, default: null },
    FDD_Payment_Type: { type: String, default: null },
    Annual_Trend_Payment_Type: { type: String, default: null },
    WBC_Payment_Type: { type: String, default: null },
    RD_Payment_Type: { type: String, default: null },
    WFR_Payment_Type: { type: String, default: null },
    EV_Sorting_Payment_Type: { type: String, default: null },
    Data_Resort_Payment_Type: { type: String, default: null },
    Category_Paper: { type: String, default: null },
    Category_Online: { type: String, default: null },
    KIA_Payment_Type: { type: String, default: null },
    EV_Payment_Type: { type: String, default: null },
    CR_Payment_Type: { type: String, default: null },
    BBP_Payment_Type: { type: String, default: null },
    Report_Package_Fee_Paid: { type: Boolean, default: null },
    FDD_Fee: { type: String },
    total_sent_surveys: { type: Number },
    surveys_completed: { type: Number },
    response_rate: { type: Number },
    deal: { type: mongoose.Schema.Types.Date, default: null },
    createAt: { type: mongoose.Schema.Types.Date, default: Date.now },
    updatedAt: { type: mongoose.Schema.Types.Date, default: Date.now },
  },
  {
    timestamps: { updatedAt: "updatedAt" },
  }
);

module.exports = mongoose.model("organizationprogram", OrganizationProgramSchema);
